export interface ModuleReference {
  text: string;  // APA citation text (supports *italic* for titles)
  url?: string;
  note?: string;
}

export const moduleReferences: Record<number, ModuleReference[]> = {
  1: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Clarivate. (2024). *Pulse of the library 2024.*",
      url: "https://doi.org/10.14322/pulse.of.the.library.2024",
    },
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
    {
      text: "*The New York Times Company v. Microsoft Corporation,* No. 1:23-cv-11195 (S.D.N.Y. filed Dec. 27, 2023).",
      note: "Legal citation follows Bluebook convention.",
    },
    {
      text: "Li, P., Yang, J., Islam, M. A., & Ren, S. (2023). *Making AI less \"thirsty\": Uncovering and addressing the secret water footprint of AI models.* arXiv:2304.03271.",
      url: "https://arxiv.org/abs/2304.03271",
    },
    {
      text: "Wang, P., Zhang, L. Y., Tzachor, A., & Chen, W.-Q. (2024). E-waste challenges of generative artificial intelligence. *Nature Computational Science, 4,* 818-823.",
      url: "https://doi.org/10.1038/s43588-024-00712-6",
    },
    {
      text: "International Energy Agency. (2025). *Energy and AI.* IEA.",
      url: "https://www.iea.org/reports/energy-and-ai",
    },
  ],

  2: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  3: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  4: [
    {
      text: "American Library Association. (2026). *Guidance on the use of artificial intelligence in libraries.*",
      url: "https://www.ala.org/tools/standards-and-guidelines/guidance-use-artificial-intelligence-libraries",
    },
    {
      text: "American Library Association. (2021). *ALA code of ethics.*",
      url: "https://www.ala.org/tools/ethics",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Association of Research Libraries. (2024). *Research libraries guiding principles for artificial intelligence.*",
      url: "https://www.arl.org/resources/research-libraries-guiding-principles-for-artificial-intelligence/",
    },
    {
      text: "*The New York Times Company v. Microsoft Corporation,* No. 1:23-cv-11195 (S.D.N.Y. filed Dec. 27, 2023).",
      note: "Legal citation follows Bluebook convention.",
    },
    {
      text: "U.S. Copyright Office. (2023, March 16). *Copyright registration guidance: Works containing material generated by artificial intelligence.* 88 Fed. Reg. 16190.",
      url: "https://www.copyright.gov/ai/ai_policy_guidance.pdf",
    },
    {
      text: "U.S. Copyright Office. (2025, January 29). *Copyright and artificial intelligence, Part 2: Copyrightability.*",
      url: "https://www.copyright.gov/ai/Copyright-and-Artificial-Intelligence-Part-2-Copyrightability-Report.pdf",
    },
  ],

  5: [
    {
      text: "American Library Association. (2026). *Guidance on the use of artificial intelligence in libraries.*",
      url: "https://www.ala.org/tools/standards-and-guidelines/guidance-use-artificial-intelligence-libraries",
    },
    {
      text: "Association of College and Research Libraries. (2016). *Framework for information literacy for higher education.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ilframework",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Estlund, K., & Hudson Vitale, C. (2026, March). *Strategic implications of AI futures for research libraries: Workshop report.* Association of Research Libraries & Coalition for Networked Information.",
      url: "https://doi.org/10.29242/report.futurescape2026",
    },
    {
      text: "Fox, V. (2025, June 11). AI refusal in libraries: A starter guide. *ACRLog.*",
      url: "https://acrlog.org/2025/06/11/ai-refusal-in-libraries-a-starter-guide/",
    },
  ],

  6: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Estlund, K., & Hudson Vitale, C. (2026, March). *Strategic implications of AI futures for research libraries: Workshop report.* Association of Research Libraries & Coalition for Networked Information.",
      url: "https://doi.org/10.29242/report.futurescape2026",
    },
    {
      text: "National Institutes of Health. (2025, July 17). *Supporting fairness and originality in NIH research applications* (NOT-OD-25-132).",
      url: "https://grants.nih.gov/grants/guide/notice-files/NOT-OD-25-132.html",
    },
    {
      text: "Government of Canada. (2025, July 28). *The use of generative artificial intelligence in the development and review of research proposals.*",
      url: "https://science.gc.ca/site/science/en/interagency-research-funding/policies-and-guidelines/use-generative-artificial-intelligence-development-and-review-research-proposals",
    },
  ],

  7: [
    {
      text: "Association of College and Research Libraries. (2016). *Framework for information literacy for higher education.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ilframework",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
  ],

  8: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "OCLC. (2025, December). *AI-assisted cataloging in WorldShare Record Manager and Connexion.*",
      url: "https://www.oclc.org/en/worldshare-record-manager.html",
      note: "Confirm exact release note URL when updating the site.",
    },
  ],

  9: [
    {
      text: "American Library Association. (2026). *Guidance on the use of artificial intelligence in libraries.*",
      url: "https://www.ala.org/tools/standards-and-guidelines/guidance-use-artificial-intelligence-libraries",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Ex Libris. (2025). *Alma Specto: AI-powered digital collections management.* Clarivate.",
      url: "https://exlibrisgroup.com/products/alma-library-services-platform/",
    },
    {
      text: "Harvard Library. (2024). *Harvard Library Collections Explorer.* Harvard University.",
      url: "https://library.harvard.edu",
      note: "Confirm direct URL for the Collections Explorer.",
    },
    {
      text: "Yale University Library. (2024). *Digital collections AI application* [Prototype]. Yale University.",
      url: "https://library.yale.edu",
      note: "Confirm direct URL for the Yale digital collections AI application.",
    },
    {
      text: "Estlund, K., & Hudson Vitale, C. (2026, March). *Strategic implications of AI futures for research libraries: Workshop report.* Association of Research Libraries & Coalition for Networked Information.",
      url: "https://doi.org/10.29242/report.futurescape2026",
    },
    {
      text: "Warner, S., & Kovari, J. (2025, January 30). *Open bibliographic metadata: A primer.* Cornell University Library.",
      url: "https://hdl.handle.net/1813/116675",
    },
    {
      text: "Enis, M. (2025, July 21). AI bots swarm library, cultural heritage sites, causing slowdowns and crashes. *Library Journal.*",
      url: "https://www.libraryjournal.com/story/ai-bots-swarm-library-cultural-heritage-sites-causing-slowdowns-and-crashes",
    },
  ],

  10: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  11: [
    {
      text: "American Library Association. (2026). *Guidance on the use of artificial intelligence in libraries.*",
      url: "https://www.ala.org/tools/standards-and-guidelines/guidance-use-artificial-intelligence-libraries",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Choice. (2024, November). *Evaluating generative AI resources: Separating the tools from the toys.* Association of College and Research Libraries.",
      url: "https://www.choice360.org/tools/evaluating-generative-ai-resources-separating-the-tools-from-the-toys/",
      note: "Includes a downloadable transparency/efficiency/critical-thinking/privacy rubric. Confirm exact URL when updating the site.",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
    {
      text: "Ithaka S+R. (2024–2025). *Generative AI product tracker.*",
      url: "https://sr.ithaka.org/our-work/generative-ai-product-tracker/",
      note: "Continuously updated; confirm current URL when updating the site.",
    },
    {
      text: "Maiberg, E. (2025, February 4). AI-generated slop is already in your public library. *404 Media.*",
      url: "https://www.404media.co/ai-generated-slop-is-already-in-your-public-library/",
    },
    {
      text: "Portillo, A., & Carson, P. (2025, January). Evaluating large language models for collection development. *Journal of the Medical Library Association, 113*(1).",
      url: "https://doi.org/10.5195/jmla.2025.2079",
    },
    {
      text: "Estlund, K., & Hudson Vitale, C. (2026, March). *Strategic implications of AI futures for research libraries: Workshop report.* Association of Research Libraries & Coalition for Networked Information.",
      url: "https://doi.org/10.29242/report.futurescape2026",
    },
    {
      text: "Stony Brook University Libraries. (2025, December 3). *Artificial intelligence use at Stony Brook University Libraries* (v. 1.4).",
      url: "https://library.stonybrook.edu/wp-content/uploads/2025/12/ArtificialIntelligenceUseatStonyBrookUniversi.html",
    },
    {
      text: "Estlund, K. (2025, October 24). When publishers' fear of AI prohibits basic uses. *Colorado State University SOURCE.*",
      url: "https://source.colostate.edu/guest-column-when-publishers-fear-of-ai-prohibits-basic-uses/",
    },
    {
      text: "Library Copyright Alliance. (2025, October). *Statement on copyright and generative artificial intelligence.*",
      url: "https://www.librarycopyrightalliance.org/documents/principles/copyright-ai/statement-on-copyright-and-generative-artificial-intelligence/",
    },
  ],

  12: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Clarivate. (2024). *Pulse of the library 2024.*",
      url: "https://doi.org/10.14322/pulse.of.the.library.2024",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
  ],

  14: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  15: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Estlund, K., & Hudson Vitale, C. (2026, March). *Strategic implications of AI futures for research libraries: Workshop report.* Association of Research Libraries & Coalition for Networked Information.",
      url: "https://doi.org/10.29242/report.futurescape2026",
    },
  ],

  16: [
    {
      text: "Karpathy, A. [@karpathy]. (2025, February 2). There's a new kind of coding I call \"vibe coding\" [Post]. X (formerly Twitter).",
      url: "https://x.com/karpathy/status/1886192184808149383",
    },
    {
      text: "Michalak, R., Dawes, T. A., & Wallace, A. (2026, May). Envisioning AI's role in libraries: Perspectives from an LIS student, a library director, and a university librarian. *College & Research Libraries News, 87*(5).",
      url: "https://crln.acrl.org/index.php/crlnews/article/view/27321",
      note: "Note: Module text attributes separate passages to \"Ava Wallace\" and \"Trevor A. Dawes\" individually. Both passages originate from this co-authored article; in-text attributions should be updated to cite all three authors or use (Michalak et al., 2026).",
    },
  ],

  17: [
    {
      text: "Ex Libris. (2025). *Alma library services platform.* Clarivate.",
      url: "https://exlibrisgroup.com/products/alma-library-services-platform/",
    },
    {
      text: "Ex Libris. (2025). *LibOW: Low-code automation for Alma.* Clarivate.",
      url: "https://exlibrisgroup.com/blog/what-is-libow/",
    },
  ],

  18: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "ALA TechSource. (n.d.). *Library technology reports.* American Library Association.",
      url: "https://www.ala.org/pubs/periodicals/ltr",
    },
    {
      text: "Association of Research Libraries. (n.d.). *ALA Core: Library and information technology association.* American Library Association.",
      url: "https://www.ala.org/core/",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
    {
      text: "Michalak, R., Dawes, T. A., & Wallace, A. (2026, May). Envisioning AI's role in libraries: Perspectives from an LIS student, a library director, and a university librarian. *College & Research Libraries News, 87*(5).",
      url: "https://crln.acrl.org/index.php/crlnews/article/view/27321",
    },
  ],

  13: [
    {
      text: "American Library Association. (2026). *Guidance on the use of artificial intelligence in libraries.*",
      url: "https://www.ala.org/tools/standards-and-guidelines/guidance-use-artificial-intelligence-libraries",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Association of Research Libraries. (2024). *ARL guiding principles for artificial intelligence.*",
      url: "https://www.arl.org/resources/arl-guiding-principles-for-artificial-intelligence/",
    },
    {
      text: "Perrigo, B. (2023, January 18). OpenAI used Kenyan workers on less than $2 per hour to make ChatGPT less toxic. *Time.*",
      url: "https://time.com/6247678/openai-chatgpt-kenya-workers/",
    },
    {
      text: "Gray, M. L., & Suri, S. (2019). *Ghost work: How to stop Silicon Valley from building a new global underclass.* Houghton Mifflin Harcourt.",
    },
    {
      text: "Williams, A., Miceli, M., & Gebru, T. (2022, October 13). The exploited labor behind artificial intelligence. *Noema Magazine.*",
      url: "https://www.noemamag.com/the-exploited-labor-behind-artificial-intelligence/",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
  ],
};
